# Generated by Django 5.1.15 on 2026-08-05 04:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('initial_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_project',
                'ordering': ('-created_at', '-project_id'),
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='planned', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'db_table': 'tbl_milestone',
                'ordering': ('sort_order', 'milestone_id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('project_cost', 'Project Cost'), ('engineering_drawing', 'Engineering Drawing'), ('contract', 'Contract'), ('report', 'Report'), ('permit', 'Permit'), ('other', 'Other')], max_length=40)),
                ('file', models.FileField(upload_to='project_documents/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('is_client_visible', models.BooleanField(default=False)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_documents', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_project_document',
                'ordering': ('-created_at', '-document_id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assignment_role', models.CharField(choices=[('project_manager', 'Project Manager'), ('client', 'Client')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_project_assignment',
                'ordering': ('project_id', 'assignment_role', 'assignment_id'),
                'constraints': [models.UniqueConstraint(fields=('project', 'user', 'assignment_role'), name='unique_project_assignment_per_user_role'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'assignment_role'), name='unique_active_project_assignment_role')],
            },
        ),
    ]
