# Generated by Django 5.1.15 on 2026-08-09 17:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='revised_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='milestone',
            field=models.ForeignKey(blank=True, db_column='milestone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.milestone'),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='assignment_role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('client', 'Client'), ('site_engineer', 'Site Engineer'), ('supervisor', 'Supervisor')], max_length=30),
        ),
        migrations.CreateModel(
            name='MilestoneExtension',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extension_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_end_date', models.DateField(blank=True, null=True)),
                ('new_end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('extended_by', models.ForeignKey(blank=True, db_column='extended_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_extensions', to='accounts.userprofile')),
                ('milestone', models.ForeignKey(db_column='milestone_id', on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='projects.milestone')),
            ],
            options={
                'db_table': 'tbl_milestone_extension',
                'ordering': ('-created_at', '-extension_id'),
            },
        ),
        migrations.CreateModel(
            name='MilestoneTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('required_worker_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('on_hold', 'On Hold')], default='planned', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_milestone_tasks', to='accounts.userprofile')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestone_tasks', to='accounts.userprofile')),
                ('milestone', models.ForeignKey(db_column='milestone_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.milestone')),
            ],
            options={
                'db_table': 'tbl_milestone_task',
                'ordering': ('sort_order', 'task_id'),
            },
        ),
        migrations.CreateModel(
            name='TaskWorkerAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('duty_instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_task_assignments', to='accounts.userprofile')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='projects.milestonetask')),
                ('worker', models.ForeignKey(db_column='worker_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_task_assignment',
                'ordering': ('-created_at', '-assignment_id'),
            },
        ),
        migrations.CreateModel(
            name='DailyTaskUpdate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('concern_text', models.TextField(blank=True)),
                ('has_safety_issue', models.BooleanField(default=False)),
                ('supervisor_review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('supervisor_review_note', models.TextField(blank=True)),
                ('supervisor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('engineer_review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('engineer_review_note', models.TextField(blank=True)),
                ('engineer_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('engineer_reviewed_by', models.ForeignKey(blank=True, db_column='engineer_reviewed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_reviewed_updates', to='accounts.userprofile')),
                ('supervisor_reviewed_by', models.ForeignKey(blank=True, db_column='supervisor_reviewed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_reviewed_updates', to='accounts.userprofile')),
                ('assignment', models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_updates', to='projects.taskworkerassignment')),
            ],
            options={
                'db_table': 'tbl_daily_task_update',
                'ordering': ('-work_date', '-created_at', '-update_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='taskworkerassignment',
            constraint=models.UniqueConstraint(fields=('task', 'worker'), name='unique_task_worker_assignment'),
        ),
        migrations.AddConstraint(
            model_name='dailytaskupdate',
            constraint=models.UniqueConstraint(fields=('assignment', 'work_date'), name='unique_task_assignment_daily_update'),
        ),
    ]
