# Generated by Django 5.1.15 on 2026-08-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
        ('projects', '0004_task_planned_manpower_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceNeed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('safety', 'Safety'), ('tools_equipment', 'Tools/Equipment'), ('ppe', 'PPE'), ('workplace_facilities', 'Workplace Facilities'), ('transportation', 'Transportation'), ('accommodation', 'Accommodation'), ('working_conditions', 'Working Conditions'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_supervisor_review', 'Under Supervisor Review'), ('verified', 'Verified'), ('forwarded_to_pm', 'Forwarded to Project Manager'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='under_supervisor_review', max_length=40)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor_remarks', models.TextField(blank=True)),
                ('supervisor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('pm_comments', models.TextField(blank=True)),
                ('pm_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('milestone', models.ForeignKey(blank=True, db_column='milestone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_needs', to='projects.milestone')),
                ('pm_reviewed_by', models.ForeignKey(blank=True, db_column='pm_reviewed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_workplace_needs', to='accounts.userprofile')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='workplace_needs', to='projects.project')),
                ('submitted_by', models.ForeignKey(db_column='submitted_by_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='workplace_needs', to='accounts.userprofile')),
                ('supervisor_reviewed_by', models.ForeignKey(blank=True, db_column='supervisor_reviewed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_workplace_needs', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_workplace_need',
                'ordering': ('-submitted_at', '-request_id'),
            },
        ),
        migrations.CreateModel(
            name='WorkplaceNeedAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='workplace_needs/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('need', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.workplaceneed')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_need_attachments', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_workplace_need_attachment',
                'ordering': ('attachment_id',),
            },
        ),
    ]
