# Generated by Django 5.1.15 on 2026-09-17 15:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
        ('projects', '0008_multi_site_engineer_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Allocated / contract value used for profit and loss comparison.', max_digits=14),
        ),
        migrations.AddField(
            model_name='milestone',
            name='planned_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected cost for this milestone, if planned.', max_digits=14),
        ),
        migrations.CreateModel(
            name='ManualMaterialExpense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='unit', max_length=40)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expense_date', models.DateField()),
                ('invoice_reference', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('approved', 'Approved')], default='approved', max_length=20)),
                ('added_by', models.ForeignKey(blank=True, db_column='added_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_material_expenses', to='accounts.userprofile')),
                ('milestone', models.ForeignKey(db_column='milestone_id', on_delete=django.db.models.deletion.CASCADE, related_name='material_expenses', to='projects.milestone')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='material_expenses', to='projects.project')),
                ('task', models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_expenses', to='projects.milestonetask')),
            ],
            options={
                'db_table': 'tbl_manual_material_expense',
                'ordering': ('-expense_date', '-expense_id'),
            },
        ),
        migrations.CreateModel(
            name='OtherProjectExpense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('equipment_rental', 'Equipment rental'), ('transportation', 'Transportation'), ('machinery', 'Machinery charges'), ('subcontractor', 'Subcontractor'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expense_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(blank=True, db_column='added_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_other_expenses', to='accounts.userprofile')),
                ('milestone', models.ForeignKey(blank=True, db_column='milestone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_expenses', to='projects.milestone')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='other_expenses', to='projects.project')),
            ],
            options={
                'db_table': 'tbl_other_project_expense',
                'ordering': ('-expense_date', '-expense_id'),
            },
        ),
        migrations.CreateModel(
            name='WorkerWageRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('daily_wage', models.DecimalField(decimal_places=2, default=Decimal('800.00'), max_digits=12)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Defaults to daily wage divided by 8 hours.', max_digits=12, null=True)),
                ('worker', models.OneToOneField(db_column='worker_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='wage_rate', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_worker_wage_rate',
                'ordering': ('worker__name',),
            },
        ),
    ]
