# Generated by Django 5.1.15 on 2026-07-28 16:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('clock_in_at', models.DateTimeField()),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('clocked_in', 'Clocked In'), ('clocked_out', 'Clocked Out')], default='clocked_in', max_length=20)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_attendance',
                'ordering': ('-clock_in_at', '-attendance_id'),
            },
        ),
        migrations.CreateModel(
            name='ManHourRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('man_hour_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('total_minutes', models.PositiveIntegerField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('attendance', models.OneToOneField(db_column='attendance_id', on_delete=django.db.models.deletion.CASCADE, related_name='man_hour_record', to='attendance.attendancerecord')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='man_hour_records', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_man_hour',
                'ordering': ('-work_date', '-man_hour_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'clocked_in')), fields=('user',), name='unique_open_attendance_per_user'),
        ),
    ]
